sudo: true
dist: bionic

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - cat version.txt
      - ./docker-build-command.sh `cat version.txt`
      - docker images
      - docker push playmice/ravencoin
