version: '3'
  
services:
  ravencoin-qt:
    image: fuzzle/ravencoin:latest
    container_name: "ravencoin-qt"
    network_mode: "bridge"
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - '~/raven:/home/raven'
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    stdin_open: true
    tty: true
    command: /usr/local/bin/raven-qt

  ravencoin:
    image: fuzzle/ravencoin:latest
    container_name: "ravencoin"
    network_mode: "bridge"
    volumes:
      - '~/raven:/home/raven'

