version: '3'
  
services:
  ravencoin-qt:
    image: playmice/ravencoin:latest
    container_name: "ravencoin-qt"
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - '~/raven:/home/ravencoin'
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    stdin_open: true
    tty: true
    command: /usr/local/bin/raven-qt

  ravencoin:
    image: playmice/ravencoin:latest
    container_name: "ravencoin"
    volumes:
      - '~/raven:/home/ravencoin'

networks:
  default:
    external:
      name: bustabit