version: 3

services:
  raven:
    container_name: raven
    image: ravencoin:1.0.0
    network_mode: "bridge"
    ports:
      - 8767:8767
    volumes:
      - '~/crypto/raven:/ravencoin'

  raven-qt:
    container_name: raven-qt
    image: fuzzle/ravencoin:1.0.2
    network_mode: "bridge"
    ports:
      - 8767:8767
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - '~/crypto/raven:/ravencoin'
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    stdin_open: true
    tty: true
    command: /opt/ravencoin/bin/raven-qt

